Frontend: Login form
chingu-voyages/v40-bears-team-37 pull request #74
Opened 2022-08-31 10:11 UTC by 12cassie34

For the issue https://github.com/chingu-voyages/v40-bears-team-37/issues/49 .

The RWD and the carousel will be in other issues.

2022-08-31 11:34 UTC, cherylli requested changes
Also, when I use a random email/password combination (not a registered user), it logs me in.

2022-08-31 11:34 UTC, cherylli commented on client/src/routes/Login.tsx
> +              <p>Thank you for login.</p>
this part seems to be is unreachable, on sucessful login, user will just be redirected to the calendar

2022-08-31 13:52 UTC, 12cassie34 commented on client/src/routes/Login.tsx
> +              <p>Thank you for login.</p>
I'm going to delete it.

2022-09-01 14:08 UTC, amirfakhrullah approved these changes, later dismissed

2022-09-06 12:33 UTC, cherylli approved these changes
works fine and error is showing now, but all axios errors on login will just be "Email or password is invalid."?

2022-09-07 11:20 UTC, merged