Simplify the auth page design
chingu-voyages/v40-bears-team-37 pull request #86
Opened 2022-09-07 11:38 UTC by 12cassie34

Simplifing the auth page design by removing the carousel view since we decided to make a static landing page.

2022-09-07 11:59 UTC, cherylli submitted a review, later dismissed
looks good

2022-09-11 11:24 UTC, AllMikeNoIke commented
LGTM! Thanks for implementing this!

2022-09-11 11:25 UTC, AllMikeNoIke approved these changes, later dismissed

2022-09-11 12:45 UTC, cherylli requested changes
![image](https://user-images.githubusercontent.com/6191116/189528218-5d139c90-73af-4e10-b464-6b1f1cab5da6.png)
Getting this error with the latest changes probably because you removed it from the styles file but the import is still there

2022-09-11 13:02 UTC, merged